services:
  - type: web
    name: planning-poker-api
    env: go
    buildCommand: go build -o bin/server .
    startCommand: ./bin/server
    plan: free
    envVars:
      - key: PORT
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DEMO_MODE
        value: "true"
      - key: JIRA_CLIENT_ID
        sync: false
      - key: JIRA_CLIENT_SECRET
        sync: false

databases:
  - name: planning-poker-db
    databaseName: planning_poker
    user: planning_poker_user
    plan: free
